# Generated by Django 3.1.4 on 2021-03-29 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Security',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, unique=True)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField()),
                ('trade_type', models.CharField(choices=[('B', 'Buy'), ('S', 'Sell')], default='B', max_length=5)),
                ('trade_price', models.FloatField()),
                ('trade_time', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfoliotrackerapp.portfolio')),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfoliotrackerapp.security')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField()),
                ('average_price', models.FloatField()),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfoliotrackerapp.portfolio')),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfoliotrackerapp.security')),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioSecurityAllocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField()),
                ('time_of_addition', models.DateTimeField(auto_now_add=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfoliotrackerapp.portfolio')),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfoliotrackerapp.security')),
            ],
        ),
        migrations.AddField(
            model_name='portfolio',
            name='securities',
            field=models.ManyToManyField(through='portfoliotrackerapp.PortfolioSecurityAllocation', to='portfoliotrackerapp.Security'),
        ),
    ]
