# Generated by Django 3.1.7 on 2021-03-30 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfoliotrackerapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='securities',
        ),
        migrations.AlterField(
            model_name='portfoliosecurityallocation',
            name='security',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='position',
            name='security',
            field=models.CharField(db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='trade',
            name='security',
            field=models.CharField(db_index=True, max_length=10),
        ),
        migrations.DeleteModel(
            name='Security',
        ),
    ]
