# Generated by Django 3.1.7 on 2021-04-11 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfoliotrackerapp', '0002_auto_20210330_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='trade_price',
            field=models.FloatField(default=100),
        ),
    ]
